#TIMINGS
ONE_TICK_TIME = 0.05

#PLAYER HEALTH
MIN_HEALTH = 10


#PLAYER PHYSICS
GROUND_Y_VEL = ( -0.078, 0.0)
FALLING_Y_VEL = (-0.6, -3.92)
STANDING_X_Z_VEL = 0.0
MAX_WALKING_VEL = 0.117859


#PLAYER YAW AND PITCH
YAW_FACING_NORTH = 180
YAW_FACING_SOUTH = 0
YAW_FACING_EAST = -90
YAW_FACING_WEST = 90
PITCH_LOOK_UP = -90
PITCH_LOOK_DOWN = 90
PITCH_LOOK_AHEAD = 0
PITCH_LOOK_INCLINED_DOWN = 30
PITCH_LOOK_INCLINED_UP = -60


#MOVEMENT
STOP_Y_LEVEL = -58
MAX_CENTER_OFFSET = (0.01,0.02)
COORDS_OFFSET = 0.5


#PRIORITY RATING
CLUSTER_DISTANCE_SCORE = 1.5
CLUSTER_SIZE_SCORE = 2


#MINING
MINING_ORE = 'diamond'
INVALID_Y_LEVEL = (-60,-64)
Y_LEVEL_LAVA_PUDDLE = -55


#SLOTS (REMEMBER TO SUBTRACT 1 TO THE REAL SLOT NUMBER)
PICKAXE_SLOT = 1
SHOVEL_SLOT = 3
WATER_BUCKET_SLOT = 4
BLOCKS_SLOT = 8


